### ISSUE TITLE
Problems meeting when running the setup.py

### ISSUE THREAD

**Issue by KisAaki** [jerryfeng2003/PointGST#1]
Hi, Thanks for your work. There is a problem when I'm running the command: cd ../emd    python setup.py install --user
It reports that:  fatal error: THC/THC.h: No such file or directory, means there is no file called THC/THC.h.
I check it on the Internet and find that it was removed since the pytorch 1.11. How do you solve this problem with a pytorch version 2.0.0?
Here are more details may be needed:
FAILED: /data2/2023/usr/PointGST-main/extensions/emd/build/temp.linux-x86_64-cpython-39/cuda/emd_kernel.o
/usr/local/cuda-11.8/bin/nvcc  -I/home/usr/miniconda3/envs/pgst/lib/python3.9/site-packages/torch/include -I/home/usr/miniconda3/envs/pgst/lib/python3.9/site-packages/torch/include/TH -I/home/usr/miniconda3/envs/pgst/lib/python3.9/site-packages/torch/include/THC -I/home/usr/miniconda3/envs/pgst/lib/python3.9/site-packages/torch/include -I/home/usr/miniconda3/envs/pgst/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -I/home/usr/miniconda3/envs/pgst/lib/python3.9/site-packages/torch/include/TH -I/home/usr/miniconda3/envs/pgst/lib/python3.9/site-packages/torch/include/THC -I/usr/local/cuda-11.8/include -I/home/usr/miniconda3/envs/pgst/include/python3.9 -c -c /data2/2023/usr/PointGST-main/extensions/emd/cuda/emd_kernel.cu -o /data2/2023/usr/PointGST-main/extensions/emd/build/temp.linux-x86_64-cpython-39/cuda/emd_kernel.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -O2 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=emd_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_89,code=compute_89 -gencode=arch=compute_89,code=sm_89 -std=c++17
/data2/2023/usr/PointGST-main/extensions/emd/cuda/emd_kernel.cu:14:10: fatal error: THC/THC.h: No such file or directory

Here is the system information I'm using:
Linux nuosen 5.15.0-89-generic #99~20.04.1-Ubuntu SMP Thu Nov 2 15:16:47 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jerryfeng2003** [comment]
Hello, thank you for your interest.
We’ve recently updated the [README.md](https://github.com/jerryfeng2003/PointGST/blob/main/README.md) to ensure the Python environment installation works correctly. Feel free to try it again.

**Comment by KisAaki** [comment]
> Hello, thank you for your interest. We’ve recently updated the [README.md](https://github.com/jerryfeng2003/PointGST/blob/main/README.md) to ensure the Python environment installation works correctly. Feel free to try it again.

Hi, I try it again but ran into the same question as before.
The reports are as:
cuda/emd_kernel.cu:14:10: fatal error: THC/THC.h: No such file or directory

**Comment by KisAaki** [comment]
> Hello, thank you for your interest. We’ve recently updated the [README.md](https://github.com/jerryfeng2003/PointGST/blob/main/README.md) to ensure the Python environment installation works correctly. Feel free to try it again.

@jerryfeng2003  The command I'm running is the:  cd ../emd    python setup.py install --user

**Comment by jerryfeng2003** [comment]
I have updated the process of installing emd, you can reclone the project and install the python environment again.
Feel free to contact me if you have any questions.

**Comment by jerryfeng2003** [comment]
@KisAaki It seems that uninstalling the ninja in the Linux system might work.
like `sudo apt remove ninja-build`

**Comment by KisAaki** [comment]
Hi, thanks for your reply. I haven't try the new project, But the reason why the problem was caused might not have something with ninja. I try the new requirements.txt which had not downloaded ninja before I do the setup, and the report also shows that couldn't find ninja in my enviroment. I guess It is still caused by the version of Pytorch.

**Comment by jerryfeng2003** [comment]
Hi @KisAaki, we have updated the extension folder and removed the dependency on THC/THC.h. Thank you for your attention.

**Comment by jerryfeng2003** [comment]
I am closing this issue. If you have any more questions, please feel free to reopen it or create a new one.

**Comment by KisAaki** [comment]
> I am closing this issue. If you have any more questions, please feel free to reopen it or create a new one.
Okay. Thanks!!!

**Comment by KisAaki** [comment]
> I am closing this issue. If you have any more questions, please feel free to reopen it or create a new one.

Okay. Thanks!!!
