### ISSUE TITLE
The few-shot learning problem

### ISSUE THREAD

**Issue by KisAaki** [jerryfeng2003/PointGST#6]
Hi, I have a question. did the result of the few-shot learning on ModelNet40 is also coming from the test process?I have tried so many times that the result from testing the few-shot learning model is so bad. Is it coming from the training process?
@jerryfeng2003

**Comment by jerryfeng2003** [comment]
Hi.
Few-shot learning on ModelNet40 is an independent task. Following previous works, such as [Point-BERT](https://github.com/Julie-tang00/Point-BERT/blob/master/cfgs/Fewshot_models/PointTransformer.yaml), [Point-MAE](https://github.com/Pang-Yatian/Point-MAE/blob/main/cfgs/fewshot.yaml), and [PointGPT](https://github.com/CGuangyan-BIT/PointGPT/blob/V1.2/cfgs/PointGPT-L/fewshot.yaml), we obtain the few-shot learning results by fine-tuning the pre-trained model on the ModelNet few-shot dataset.

**Comment by KisAaki** [comment]
Thanks for your reply. It helps me a lot.

**Comment by KisAaki** [comment]
Sorry for one more question. I didn't know how the vote works. Did I only need to add --vote when I'm doing the test or I need to use vote to train another new model?

**Comment by jerryfeng2003** [comment]
> Sorry for one more question. I didn't know how the vote works. Did I only need to add --vote when I'm doing the test or I need to use vote to train another new model?

You only need to add `--vote` while testing the fine-tuned model. Just like the following codes.
`CUDA_VISIBLE_DEVICES=<GPUs> python main.py --test --vote --config cfgs/finetune_modelnet.yaml --exp_name <output_file_name> --ckpts <path/to/best/fine-tuned/model>`

**Comment by KisAaki** [comment]
Thanks a lot. Im so surprised how your model is so small. When using PointGPT-L as the baseline, How did the 2.4M come? I'm a little curious about what things should be calculated and what not. Did it only includes the up linear, down linear and the apater for training? Should it be multiplied by 12 or 24(for the depth of the Transformer)?
Thanks again for your reply again.

**Comment by jerryfeng2003** [comment]
> Thanks a lot. Im so surprised how your model is so small. When using PointGPT-L as the baseline, How did the 2.4M come? I'm a little curious about what things should be calculated and what not. Did it only includes the up linear, down linear and the apater for training? Should it be multiplied by 12 or 24(for the depth of the Transformer)? Thanks for your reply again.

2.4M is the trainable parameter containing the adapters and the MLP classifier. We construct adapters for each block. So the total trainable parameters are the parameters for an adapter multiplied by 24 and added to the classifier head.

**Comment by jerryfeng2003** [comment]
I am closing this issue. If you have any more questions, please feel free to reopen it or create a new one.
